<?php

namespace Database\Seeders;

use App\Models\ProductDetail;
use Illuminate\Database\Seeder;

class ProductDetailsTableSeeder extends Seeder
{
    public function run()
    {
        $product_details = [
            [
                'id'                => 1,
                'product_code_name' => 'A01',
                'product_color'     => 'สีแดง',
                'product_size'      => 'S',
                'balance_amount'    => 50,
                'total_amount'      => 500,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 2,
                'product_code_name' => 'A01',
                'product_color'     => 'สีดำ',
                'product_size'      => 'M',
                'balance_amount'    => 1250,
                'total_amount'      => 2000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 3,
                'product_code_name' => 'A01',
                'product_color'     => 'สีครีม',
                'product_size'      => 'L',
                'balance_amount'    => 7,
                'total_amount'      => 100,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 4,
                'product_code_name' => 'A01',
                'product_color'     => 'สีม่วง',
                'product_size'      => 'S',
                'balance_amount'    => 1000,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 5,
                'product_code_name' => 'A01',
                'product_color'     => 'สีเหลือง',
                'product_size'      => 'M',
                'balance_amount'    => 500,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 6,
                'product_code_name' => 'A01',
                'product_color'     => 'สีขาว',
                'product_size'      => 'XL',
                'balance_amount'    => 500,
                'total_amount'      => 500,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 7,
                'product_code_name' => 'A02',
                'product_color'     => 'สีชมพู',
                'product_size'      => '-',
                'balance_amount'    => 250,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 8,
                'product_code_name' => 'A02',
                'product_color'     => 'สีเหลือง',
                'product_size'      => '-',
                'balance_amount'    => 10,
                'total_amount'      => 700,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 9,
                'product_code_name' => 'A02',
                'product_color'     => 'สีฟ้า',
                'product_size'      => '-',
                'balance_amount'    => 10,
                'total_amount'      => 550,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 10,
                'product_code_name' => 'A02',
                'product_color'     => 'สีขาว',
                'product_size'      => '-',
                'balance_amount'    => 4,
                'total_amount'      => 120,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 11,
                'product_code_name' => 'A03',
                'product_color'     => 'สีชมพู',
                'product_size'      => 'M',
                'balance_amount'    => 4,
                'total_amount'      => 10,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 12,
                'product_code_name' => 'A03',
                'product_color'     => 'สีฟ้า',
                'product_size'      => 'M',
                'balance_amount'    => 7,
                'total_amount'      => 10,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 13,
                'product_code_name' => 'A03',
                'product_color'     => 'สีเหลือง',
                'product_size'      => 'M',
                'balance_amount'    => 1,
                'total_amount'      => 10,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 14,
                'product_code_name' => 'A04',
                'product_color'     => 'สีส้ม',
                'product_size'      => 'XL',
                'balance_amount'    => 0,
                'total_amount'      => 50,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 15,
                'product_code_name' => 'A04',
                'product_color'     => 'สีน้ำเงิน',
                'product_size'      => 'XL',
                'balance_amount'    => 0,
                'total_amount'      => 50,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 16,
                'product_code_name' => 'A04',
                'product_color'     => 'สีชมพู',
                'product_size'      => 'XL',
                'balance_amount'    => 1,
                'total_amount'      => 50,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 17,
                'product_code_name' => 'B01',
                'product_color'     => 'สีดำ',
                'product_size'      => 'S',
                'balance_amount'    => 27,
                'total_amount'      => 100,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 18,
                'product_code_name' => 'B01',
                'product_color'     => 'สีขาว',
                'product_size'      => 'M',
                'balance_amount'    => 57,
                'total_amount'      => 100,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 19,
                'product_code_name' => 'B01',
                'product_color'     => 'สีน้ำตาล',
                'product_size'      => 'L',
                'balance_amount'    => 17,
                'total_amount'      => 100,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 20,
                'product_code_name' => 'B01',
                'product_color'     => 'สีลายดำ-ขาว',
                'product_size'      => 'XL',
                'balance_amount'    => 90,
                'total_amount'      => 100,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 21,
                'product_code_name' => 'C01',
                'product_color'     => 'สีกรม',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 22,
                'product_code_name' => 'C01',
                'product_color'     => 'สีขาว',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 23,
                'product_code_name' => 'C01',
                'product_color'     => 'สีแสด',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 24,
                'product_code_name' => 'C01',
                'product_color'     => 'สีมิ้น',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 25,
                'product_code_name' => 'C01',
                'product_color'     => 'สีเทา',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 26,
                'product_code_name' => 'C01',
                'product_color'     => 'สีมุก',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
            [
                'id'                => 27,
                'product_code_name' => 'C01',
                'product_color'     => 'สีดำ',
                'product_size'      => '-',
                'balance_amount'    => 999,
                'total_amount'      => 1000,
                'created_at'        => '2021-11-18 18:05:00',
                'updated_at'        => '2021-11-18 18:05:00',
            ],
        ];

        ProductDetail::insert($product_details);
    }
}
